# -*- coding: utf-8 -*-
"""PREDIKSI7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NBCqxAPJe551nfSR1f-Sry58oI5ePEi

BUSINNES UNDERSTANDING
"""

# Manipulasi Data
import pandas as pd
import numpy as np

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Pengaturan Tampilan
pd.set_option('display.max_columns', None)

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/DATARILL/DATAFIKS.xlsx"

df = pd.read_excel(path)

df.head()
print(f"Jumlah baris dan kolom: {df.shape}")

#INFORMASI Dataset
df.info()

print(df.describe())

#cek missing value
df.isnull().sum()

print("Jumlah Missing Value")
print(df.isnull().sum())

#cek duplicate
df.duplicated().sum()

print("Jumlah Data Duplikat :", df.duplicated().sum())

# Distribusi variabel target
plt.figure(figsize=(8,5))

sns.histplot(
    df['Jumlah_Kriminalitas'],
    bins=10,      # karena datanya cuma 30 baris
    kde=True
)

plt.title('Distribusi Estimasi Jumlah Kriminalitas')
plt.xlabel('Estimasi Jumlah Kriminalitas')
plt.ylabel('Frekuensi')

plt.show()

#korelasi antar variabel
plt.figure(figsize=(8,6))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='Blues',
    fmt=".2f"
)

plt.title("Heatmap Korelasi")

plt.show()

#karena tujuan penelitian ini adalah menggunaka 4 variabel utama, seperti kepadatan penduduk, persentase pendidikan, jumlah individu p3ke
# dan estimasi jumlah pengangguran, maka variabel yang lain pada heatmap akan dihapus

kolom = [
    'Kepadatan_Penduduk',
    'PENDIDIKAN',
    'P3KE',
    'Pengangguran_Estimasi',
    'Jumlah_Kriminalitas'
]

plt.figure(figsize=(8,6))

sns.heatmap(
    df[kolom].corr(),
    annot=True,
    cmap='Blues',
    fmt=".2f",
    linewidths=0.5,
    square=True
)

plt.title("Heatmap Korelasi Antar Variabel")
plt.tight_layout()

plt.show()

df["Jumlah_Kriminalitas"].describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.hist(df["Jumlah_Kriminalitas"], bins=10)
plt.xlabel("Jumlah Kriminalitas")
plt.ylabel("Frekuensi")
plt.title("Distribusi Jumlah Kriminalitas")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

fitur = [
    "Kepadatan_Penduduk",
    "PENDIDIKAN",
    "P3KE",
    "Pengangguran_Estimasi"
]

for kolom in fitur:
    plt.figure(figsize=(6,4))
    sns.scatterplot(data=df, x=kolom, y="Jumlah_Kriminalitas")
    plt.title(f"{kolom} vs Jumlah Kriminalitas")
    plt.show()

df[df["Jumlah_Kriminalitas"] == df["Jumlah_Kriminalitas"].max()]

"""DATA PREPARATION"""

X = df[[
    "Kepadatan_Penduduk",
    "PENDIDIKAN",
    "P3KE",
    "Pengangguran_Estimasi"
]]

y = df["Jumlah_Kriminalitas"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Jumlah Data Latih :", len(X_train))
print("Jumlah Data Uji   :", len(X_test))

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print(y_pred)

feature_importance = pd.DataFrame({
    'Variabel': X.columns,
    'Importance': rf.feature_importances_
})

print(feature_importance)

hasil_prediksi = pd.DataFrame({
    'Aktual': y_test,
    'Prediksi': y_pred
})

hasil_prediksi

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE :", rmse)
print("R² :", r2)

from sklearn.model_selection import cross_val_score

cv = cross_val_score(
    rf,
    X,
    y,
    cv=5,
    scoring="r2"
)

print(cv)
print("Rata-rata R² :", cv.mean())

import pandas as pd

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(
    importance["Feature"],
    importance["Importance"]
)

plt.title("Feature Importance")
plt.xlabel("Variabel")
plt.ylabel("Nilai Importance")

plt.show()

feature_importance = pd.DataFrame({
    'Variabel': X.columns,
    'Importance': rf.feature_importances_
})

print(feature_importance)

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df[[
        "Kepadatan_Penduduk",
        "PENDIDIKAN",
        "P3KE",
        "Pengangguran_Estimasi",
        "Jumlah_Kriminalitas"
    ]]
)

plt.title("Boxplot Variabel Penelitian")
plt.xticks(rotation=20)
plt.show()

plt.figure(figsize=(6,6))

plt.scatter(y_test, y_pred)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Nilai Aktual")
plt.ylabel("Nilai Prediksi")
plt.title("Perbandingan Nilai Aktual dan Prediksi")

plt.show()

residual = y_test - y_pred

plt.figure(figsize=(6,4))

plt.scatter(y_pred, residual)

plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)

plt.xlabel("Nilai Prediksi")
plt.ylabel("Residual")
plt.title("Residual Plot")

plt.show()

hasil = pd.DataFrame({
    "Aktual": y_test,
    "Prediksi": y_pred
})

print(hasil.head(10))

#HASIL EVALUASI MODEL
print("="*40)
print("HASIL EVALUASI MODEL")
print("="*40)

print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R²   : {r2:.4f}")

print("\nCross Validation (R²)")
print(cv)
print(f"Rata-rata Cross Validation : {cv.mean():.4f}")

# FEATURE IMPORTANCE
print("="*40)
print("FEATURE IMPORTANCE")
print("="*40)

print(importance)

hasil = pd.DataFrame({
    "Aktual": y_test.values,
    "Prediksi": y_pred
})

print("="*40)
print("HASIL PREDIKSI")
print("="*40)

print(hasil.head(10))

print(df.shape)